apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  properties:
    flow:
      - name: kafka.bootstrap.servers
        value: kafka.default.svc.cluster.local:9092
      - name: quarkus.kafka.devservices.enabled
        value: "false"
  build:
    template:
      buildArgs:
        - name: QUARKUS_EXTENSIONS
          value: io.quarkus:quarkus-messaging-kafka
    config:
      strategy: operator
